//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourismpk.Models
{
    using System;
    using System.Web;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Package()
        {
            this.bookings = new HashSet<booking>();
        }
    
        public int Pkg_Id { get; set; }
        public Nullable<int> room_no { get; set; }
        public string Pkg_Name { get; set; }
        public Nullable<int> pkg_capacity { get; set; }
        public string Pkg_Type { get; set; }
        public string Pkg_Location { get; set; }
        public string Pkg_Price { get; set; }
        public Nullable<int> Tourist_Id { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public Nullable<System.DateTime> Updation_Date { get; set; }
        public string Pkg_Pic { get; set; }

        [NotMapped]
        public HttpPostedFileBase Pkgd_Pic { get; set; }
        public Nullable<int> Cat_Fid { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking> bookings { get; set; }
        public virtual Category Category { get; set; }
    }
}
