//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourismpk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tourist
    {
        public int Tourist_Id { get; set; }
        public string Tourist_FirstName { get; set; }
        public string Tourist_LastName { get; set; }
        public string Tourist_Email { get; set; }
        public string Tourist_Password { get; set; }
        public string Tourist_Contact { get; set; }
        public string Tourist_Address { get; set; }
    }
}
